### ISSUE TITLE
stack build/run failure

### ISSUE THREAD

**Issue by uNouss** [camfort/fortran-src-aeson#1]
Hello,

When I try to build it locally, or try to run it with stack like:
 - `$ stack build` 
 - `$ stack run -- -v 77e encode input.f`, ([input.f](https://github.com/camfort/fortran-src/files/8494748/big_ints_real.f.txt))

I encounter this issue

```bash
/Users/User/Documents/fortran-src-aeson/package.yaml: Ignoring unrecognized field $.language
Specified file "README.md" for extra-source-files does not exist
Specified file "CHANGELOG.md" for extra-source-files does not exist
Cloning d907e78e92377b19329769e8363ebe2980eea2c9 from https://github.com/camfort/fortran-src
Received ExitFailure 128 when running
Raw command: /usr/local/bin/git reset --hard d907e78e92377b19329769e8363ebe2980eea2c9
Run from: /private/var/folders/sc/kb01bvn566z1qpv1pjvkz1nh0000gp/T/with-repo4540/cloned
Standard error:

fatal: Impossible d'analyser l'objet 'd907e78e92377b19329769e8363ebe2980eea2c9'.
```
> Current Stack version: 2.7.5, available download version: 2.7.5

**Comment by raehik** [comment]
Argh, thanks - this repo was relying on some unmerged fortran-src changes, and now that they got merged the commit changed. This should be fixed on the latest `main` commit!

**Comment by dorchard** [comment]
@uNouss can you confirm this okay for you now so we can close this issue?

**Comment by raehik** [comment]
there was a short update from @uNouss in https://github.com/camfort/fortran-src/issues/215 - I'm archiving this repo to avoid any confusion (it all got merged into [fortran-src-extras](https://github.com/camfort/fortran-src-extras)) so please take any further discussion there!
